### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by cold-hr** [Stolao/Npc_Release#17]
I want you to customize the script.
https://github.com/rathena/rathena/blob/master/npc/custom/woe_controller.txt

Want a menu For customization Castle
Set class1 / class 2 / hiclass / 3rd class.
And the status as status 255/355/455 and so on.

thank you so much.

**Comment by Stolao** [comment]
This is not a request forum if you have a request kindly post it on the rAthena website in the script request section

**Comment by cold-hr** [comment]
Ok thank
