### ISSUE TITLE
wrong formula

### ISSUE THREAD

**Issue by Miraakol** [Stolao/Npc_Release#20]
daily reward:

"0|0|0|0|6608|30",

must give me a item 6608 30 pcs but when i log in it gives me job exp i guess

im using latest rev.

**Comment by Stolao** [comment]
Show entire conf, and the revision number of script as well as rAthena git hash, "Latest" is not a valid number.

I'll try and reproduce myself once I'm home.

**Comment by Miraakol** [comment]
actually sir im using idathena so i dont know what git hash they are using. about na conf im using the default one.

**Comment by Miraakol** [comment]
@Stolao did you try it alreaduy sir? :)

**Comment by Stolao** [comment]
Sorry for late response I forgot I changed formatting and didn't mention it in notes, it went from "0|0|0|0" to "0,0,0,0"


It's been updated in master now.
