### ISSUE TITLE
Weapon Mastery System (less code issues, more gameplay-issues =P)

### ISSUE THREAD

**Issue by Fraterna** [Stolao/Npc_Release#22]
yo!
i love your weapon mastery system, overall it's really great. hence it has 2 minor flaws:

1.) Archbishop's Judgement Set:
the Judgement-set is mainly used for Adoramus-builds (barely see any aspd-ABs using it), but it activates Onslaught, because, well, Judgement-weapon is a mace. would it be possible to add some 'exception-list' to stuff some weapon-IDs in to "force" them using another mastery? 
this would also be great for melee-bards (using a berserk-guitar that usually would use Ranged mastery but isn't as useful for that) or some other 'for fun builds'.

2.) Swiftness' Doubleattack
it actually interferes with Assassin's crit builds, especially doubledagger, it often happens to miss a lot because hit is too low but doubleattack triggers. 
no idea what would be better. maybe a luck-bonus? some magic evasion? no idea, thought.

**Comment by Stolao** [comment]
Its balanced around my server it's easy to edit and stuff for your personal preferences, as for an exception list I would prefer not to do this as these functions are called often and don't want to big it down even more then it is.

If you need help editing I can show you how.

Also if you want you can call one of the mastery functions via an item to give that item special bonuses. Though it will end up with 2 bonuses then.
