### ISSUE TITLE
hey stolao thank you again for all the support on your scripts but here is an the issues that happen

### ISSUE THREAD

**Issue by sikiro** [Stolao/Npc_Release#23]
![image](https://cloud.githubusercontent.com/assets/9375953/25784867/73c782b6-3342-11e7-8ac2-3d27a9db0df5.png)

it also seems to be turning the item into an apple  and its not classified as consumable.

**Comment by Stolao** [comment]
After remaining it should be "; not ; my bad typo, I'll fix once home

**Comment by sikiro** [comment]
yeah added that command works ingame and such but when u double click the endless fly wing item nothing happens. it wont refill it or anything.

**Comment by sikiro** [comment]
[11:01 AM] Stolao: Ya that's what I thought
[11:02 AM] Stolao: I can probably make a fake command similar that instead identifes 1 item but you can't pick
[11:02 AM] Stolao: Or all items but uses that many changes

as requested leaving you a note.

willl identify but still consume.
