### ISSUE TITLE
Stolao please take a look at this

### ISSUE THREAD

**Issue by HexAbleSec** [Stolao/Npc_Release#26]
this one is from auto event

after every event it shows this

![image](https://user-images.githubusercontent.com/31078767/29482573-3891fe0e-8448-11e7-90bb-018c951908ef.png)

**Comment by Stolao** [comment]
ya this has to do with the rewrite of the mail system, we are currently working on getting a  send mail function on scripts without the need of a SQl query, Once that is implemented ill update the script, till then set `	$@Mail = 1;	// Toggle [1] = Mail [0] = Direct to inv` to 0

**Comment by HexAbleSec** [comment]
ok thank you
